name: Discord Notifications

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: fjogeleit/http-request-action@v1.1.0
        with:
          url: 'https://discord.com/api/webhooks/1334053000850833430/PqhAHYFO9DP5KMYZXqgU0StHP6gXPFrHt00oSdrkfXrpmaeqJDbfEySos3i5mjXnE4su'
          method: 'POST'
          headers: 'Content-Type: application/json'
          data: '{"content": "A new pull request has been created: ${{ github.event.pull_request.html_url }}"}'
